version: '2'
services:
    gnomeserver-app:
        image: gnomeserver
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gnomeserver-postgresql:5432/gnomeServer
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gnomeserver-postgresql:
        extends:
            file: postgresql.yml
            service: gnomeserver-postgresql
